### PR TITLE
Create rule-2.txt

### PR DESCRIPTION
**Pull request by mhessoct**

### CODE REVIEW

**Comment by clmay** [comment]
This rule is clearly in violation of Rule 1. Rule 1 states "You must change this rule." in reference to Rule 1 itself.

**Comment by clmay** [comment]
Perhaps you can provide a fix by proposing an amendment to Rule 1, instead of this change?

**Comment by clmay** [comment]
Closing this until the conflict with Rule 1 is addressed. :P

**Comment by mhessoct** [comment]
@clmay I didn't address the conflict with Rule 1 yet! ??

**Comment by clmay** [comment]
Fine, fine, I'll close this again. It's clearly a violation of the ruleset, as it stands.

**Pull request closed without merging**
